import {el, panel, table} from './ui.js';
const repo = 'https://github.com/bsisduck/laya-sec-agent/blob/main/';
export const standardsEvidence = [
  {framework: 'RODO / GDPR · Article 9', source: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng', control: 'Classification ACLs and input/output filtering restrict governed data paths.', evidence: ['docs/document-slice.md', 'tests/test_gateway.py'], gap: 'Data labels are not a legal basis for special-category processing. Controller must establish an applicable condition and safeguards.'},
  {framework: 'RODO / GDPR · Article 22', source: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng', control: 'Exact-action approvals bind payload and authority; hard denials cannot be overridden.', evidence: ['docs/delegated-authority.md', 'tests/test_authority.py'], gap: 'A review click does not establish Article 22 compliance or meaningful human involvement. Assess automated decisions, effects, exceptions and data-subject safeguards.'},
  {framework: 'AI Act · Annex III point 4 / Article 6', source: 'https://eur-lex.europa.eu/eli/reg/2024/1689/2026-07-27/eng', control: 'Scoped authority and immutable audit support investigation of a defined use.', evidence: ['docs/delegated-authority.md'], gap: 'HR use alone does not establish high-risk classification. Intended purpose and applicable exceptions matter; assess the actual system and use.'},
  {framework: 'AI Act · Article 12', source: 'https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-12', control: 'Durable intent and terminal audit are transactional with governed ledgers.', evidence: ['docs/budgets.md', 'tests/test_models.py'], gap: 'Local minimized logs do not establish full system traceability, required retention or every high-risk logging obligation.'},
  {framework: 'AI Act · Article 14', source: 'https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-14', control: 'Operator exact-action review and deterministic deny controls.', evidence: ['docs/scoped-tools.md', 'tests/test_authority.py'], gap: 'Competence, authority, monitoring, interpretation, intervention and automation-bias safeguards need organizational and system-specific evidence.'},
  {framework: 'AI Act · Article 26', source: 'https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-26', control: 'Privileged operations UI shows actual protected activity and unresolved reservations.', evidence: ['docs/control-plane-contract.md', 'docs/telemetry-delivery.md'], gap: 'Deployer instructions, monitoring, notifications and other applicable obligations remain. No automatic compliance claim.', context: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'},
  {framework: 'DORA · ICT risk / incidents / testing / third parties', source: 'https://www.esma.europa.eu/publications-and-data/interactive-single-rulebook/dora', control: 'Bounded controls, retained uncertain work, deterministic failure tests and a local collector contract lab.', evidence: ['docs/budgets.md', 'docs/telemetry-delivery.md', 'tests/test_models.py'], gap: 'Entity-level ICT governance, incident classification/reporting, resilience testing and third-party arrangements require separate evidence. No bank integration or universal SIEM delivery.'},
  {framework: 'OWASP LLM Top 10 · edition 2025', source: 'https://genai.owasp.org/llm-top-10/', control: 'LLM02 sensitive information disclosure: filtering. LLM06 excessive agency: scoped execution. LLM10 unbounded consumption: reservations and freeze.', evidence: ['docs/threat-model.md', 'tests/test_models.py'], gap: 'Versioned control associations, not certification, an attack count or proof of general model safety.'},
  {framework: 'OWASP Agentic Top 10 · edition 2026', source: 'https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/', control: 'ASI02 tool misuse / ASI03 identity and privilege: exact grants and execution boundaries; ASI09 trust exploitation: exact approval context.', evidence: ['docs/threat-model.md', 'tests/test_authority.py'], gap: 'Association with implemented controls; native host paths and ungoverned agents remain outside coverage.'},
];
const link = (title, href) => el('a', {href, target: '_blank', rel: 'noopener noreferrer'}, title);
export function standardsView() {
  return panel('Standards controls, evidence and gaps', el('p', {class: 'hint'}, 'Evidence associations for review. Applicability depends on purpose and deployment. No compliance badge, certification, legal risk score or implementation-deadline claim. OWASP editions are explicitly 2025 / 2026.'),
    table(['Framework / official source', 'Relevant implemented control', 'Local executable / documented evidence', 'Remaining obligation'], standardsEvidence.map(row => [
      el('div', {}, link(row.framework, row.source), row.context ? el('p', {}, link('Official Commission context', row.context)) : null), row.control,
      el('div', {}, row.evidence.map(path => el('p', {}, link(path, repo + path)))), row.gap,
    ])));
}
